### ISSUE TITLE
Excessively high 'polkitd' CPU usage under ubuntu-desktop

### ISSUE THREAD

**Issue by gimmx** [TheRemote/Ubuntu-Server-raspi4-unofficial#80] opened 2019-11-10 02:11 UTC
Followed your instructions on a Raspberry Pi 4B. I installed xrdp with ubuntu-desktop and 'polkitd' runs at 60-90% CPU, making the connection almost worthless.

Also connecting as the user UBUNTU causes a flood of authentication requests. I was forced to use root to setup the wifi without having to enter the password a dozen times.

**Comment by TheRemote** [comment] 2019-11-11 18:45
Interesting.  I think this is a groups issue (either regular groups or possibly udev groups) as I have seen warnings in the logs about xrdp groups possibly missing/configured incorrectly.  I'll put this on the fix list for the next release and see if we can't get that service fixed up.

**Comment by TheRemote** [comment] 2019-11-11 23:08
So I haven't been able to reproduce this yet.  Let me outline my steps.

Wrote my preinstalled desktop v21 image to SD card
Started up Pi (connected to a monitor)
SSH'd in with Putty and installed xrdp using apt install xrdp
Connected with RDP from Windows 10, signed in with default Xorg option, ubuntu/newpass entered as account

It went right in, CPU usage at about 2-8%.  Screenshot attached.  What did I do differently?
![RDPTest](https://user-images.githubusercontent.com/15236457/68628309-7060f380-049d-11ea-9bea-3a47ba75157b.png)

**Comment by TheRemote** [comment] 2019-11-11 23:19
Ok, I tried this headless with no monitor attached and am getting the high polkitd usage, but no authentication issues, so it appears at least the polkitd issue is triggered by not having any monitor attached to the Pi

**Comment by gimmx** [comment] 2019-11-11 23:20
Yes I should've been more specific. I'm running headless.

**Comment by TheRemote** [comment] 2019-11-11 23:28
No worries, I am now seeing it too, if I connect it to a monitor and reboot everything goes back to normal so it appears that it is not happy at all if it's headless.  I'll see what we can do to get that fixed!

**Comment by TheRemote** [comment] 2019-11-17 15:56
So this one is turning out to  be a little bit of a can of worms.  The problem seems to be that without a display connected the video subsystem isn't loading which gets into drivers and things like that.

I'm going to leave this open until I nail it but it may take some more time as it goes pretty deep!

**Comment by TheRemote** [comment] 2019-11-22 05:10
I've made some progress here, can you try with v23?

**Comment by TheRemote** [comment] 2019-11-22 05:21
This has been fixed in v23

**Closed as completed by TheRemote** 2019-11-22 05:21 UTC
